# Generated by Django 3.1.7 on 2021-03-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_added',
        ),
    ]
