# Generated by Django 3.1.7 on 2021-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_address_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer',
            new_name='user',
        ),
    ]
