# Generated by Django 3.1.7 on 2021-03-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210327_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
