# Generated by Django 3.1.7 on 2021-03-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210328_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comlete',
            new_name='complete',
        ),
    ]
