# Generated by Django 3.1.7 on 2021-05-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donateme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('descp', models.TextField(max_length=250)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('fund_req', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('monthly_inc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('monthly_exp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('donated_on', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donateme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.donateme')),
            ],
        ),
    ]
