# Generated by Django 3.1.7 on 2021-05-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210504_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateme',
            old_name='is_verified',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='donateme',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='donateme',
            name='monthly_exp',
        ),
        migrations.RemoveField(
            model_name='donateme',
            name='monthly_inc',
        ),
        migrations.AlterField(
            model_name='supplies',
            name='status',
            field=models.CharField(choices=[('Processing Initiated', 'Processing Initiated'), ('Checking Quality', 'Checking Quality'), ('Supplies Accepted', 'Supplies Accepted')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('monthly_inc', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('monthly_exp', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
