# Generated by Django 3.1.7 on 2021-05-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_aboutme_descp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply', to='store.supplies'),
        ),
    ]
